apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-config
  labels:
    {{ include "labels" . | indent 4 }}
data:
  # put application default configs here
  application.yml: |
    server:
      port: {{ .Values.service.port }}
