apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
