apiVersion: v2
name: grafana
description: A wrapper chart for Grafana
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: grafana
    version: 8.6.4
    repository: https://grafana.github.io/helm-charts
